{% set name = "motuclient" %}
{% set version = "1.8.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/motuclient-{{ version }}.tar.gz
  sha256: c89f8dcb348ce8232b7fa5b37d531623fa8dca0263841a09c044e19777202c5d

build:
  number: 0
  noarch: python
  entry_points:
    - motuclient = motuclient:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - motu_utils
  commands:
    - pip check
    - motuclient --help
  requires:
    - pip

about:
  home: https://github.com/clstoulouse/motu-client-python
  summary: Extract and download gridded data through a python command line from Motu web server. Used in CMEMS context http://marine.copernicus.eu/
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
