{% set name = "motuclient" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/motuclient-{{ version }}.tar.gz
  sha256: 9ef1f34b9866caff760f9b3218b62bd11aaa7b5da5844308a968004752940d8f

build:
  entry_points:
    - motuclient = motuclient.motuclient:main
    - motu-client = motuclient.motuclient:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil

test:
  imports:
    - motu_utils
    - motuclient
  commands:
    - pip check
    - motuclient --help
    - motu-client --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/clstoulouse/motu-client-python
  summary: Extract and download gridded data through a python command line from Motu web server. Used in CMEMS context http://marine.copernicus.eu/
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - ocefpaf
